// Demo data — used when Supabase is not yet connected.
// Once you add your .env credentials this is bypassed and real DB data is used.

export const DEMO_CLIENTS = [
  {
    id: '1',
    company: 'Arrow Auto Glass',
    alias: 'Arrow',
    email: 'arrow@resourcemedia.net',
    facebook_url: 'https://facebook.com/arrowautoglass',
    google_drive_url: '#',
    status: 'active',
    transition_status: null,
    notes: 'Long-term client. Monthly FB posts + annual email campaigns.',
    created_at: '2023-01-15',
  },
  {
    id: '2',
    company: 'Savory Commercial',
    alias: 'Savory',
    email: 'savory@resourcemedia.net',
    facebook_url: 'https://facebook.com/savorycommercial',
    google_drive_url: '#',
    status: 'active',
    transition_status: 'In Progress',
    notes: 'Website upgrade in progress. Seasonal campaigns.',
    created_at: '2023-06-01',
  },
  {
    id: '3',
    company: 'WQI Plumbing',
    alias: 'WQI',
    email: 'wqi@resourcemedia.net',
    facebook_url: null,
    google_drive_url: '#',
    status: 'active',
    transition_status: null,
    notes: 'New blog launch. SEO-focused content strategy.',
    created_at: '2024-02-10',
  },
  {
    id: '4',
    company: 'Flags Plus',
    alias: 'Flags',
    email: 'flags@resourcemedia.net',
    facebook_url: null,
    google_drive_url: '#',
    status: 'active',
    transition_status: null,
    notes: 'Print-heavy client. Seasonal brochures and event flags.',
    created_at: '2023-09-20',
  },
  {
    id: '5',
    company: 'Resource Media',
    alias: 'RM',
    email: 'jim@resourcemedia.net',
    facebook_url: 'https://facebook.com/resourcemedia',
    google_drive_url: '#',
    status: 'active',
    transition_status: null,
    notes: 'Internal account.',
    created_at: '2022-01-01',
  },
]

export const DEMO_PROJECTS = [
  {
    id: '1',
    project_number: '8037',
    name: 'FB Posts 52',
    client_id: '1',
    client: { company: 'Arrow Auto Glass', alias: 'Arrow' },
    product_type: 'CO',
    priority: 'Hot All',
    area: 'Social',
    est_status: 'Open',
    proof_status: 'Approved',
    inv_status: 'Open',
    collect_status: 'Open',
    est_amount: 1200,
    client_owed: 1200,
    client_paid: 0,
    team_owed: 400,
    team_paid: 0,
    start_date: '2026-03-01',
    end_date: '2026-03-31',
    created_at: '2026-03-01',
  },
  {
    id: '2',
    project_number: '7993',
    name: 'Brochure',
    client_id: '4',
    client: { company: 'Flags Plus', alias: 'Flags' },
    product_type: 'DS',
    priority: 'Now',
    area: 'Print',
    est_status: 'Open',
    proof_status: 'Revise',
    inv_status: 'Open',
    collect_status: 'Open',
    est_amount: 850,
    client_owed: 850,
    client_paid: 0,
    team_owed: 280,
    team_paid: 0,
    start_date: '2026-02-15',
    end_date: '2026-04-01',
    created_at: '2026-02-15',
  },
  {
    id: '3',
    project_number: '7977',
    name: 'Blog Launch',
    client_id: '3',
    client: { company: 'WQI Plumbing', alias: 'WQI' },
    product_type: 'ST',
    priority: 'Hot Area',
    area: 'Web',
    est_status: 'Open',
    proof_status: 'Approved',
    inv_status: 'Paid',
    collect_status: 'Approved',
    est_amount: 600,
    client_owed: 0,
    client_paid: 600,
    team_owed: 200,
    team_paid: 200,
    start_date: '2026-01-10',
    end_date: '2026-03-15',
    created_at: '2026-01-10',
  },
  {
    id: '4',
    project_number: '7353',
    name: 'Website Upgrade',
    client_id: '2',
    client: { company: 'Savory Commercial', alias: 'Savory' },
    product_type: 'ST',
    priority: 'Hot All',
    area: 'Web',
    est_status: 'Open',
    proof_status: 'In Progress',
    inv_status: 'Open',
    collect_status: 'Open',
    est_amount: 3200,
    client_owed: 1600,
    client_paid: 1600,
    team_owed: 1000,
    team_paid: 500,
    start_date: '2025-11-01',
    end_date: '2026-04-30',
    created_at: '2025-11-01',
  },
  {
    id: '5',
    project_number: '8026',
    name: 'FB Posts 51',
    client_id: '1',
    client: { company: 'Arrow Auto Glass', alias: 'Arrow' },
    product_type: 'CO',
    priority: 'Normal',
    area: 'Social',
    est_status: 'Open',
    proof_status: 'Approved',
    inv_status: 'Open',
    collect_status: 'Open',
    est_amount: 1200,
    client_owed: 1200,
    client_paid: 0,
    team_owed: 400,
    team_paid: 0,
    start_date: '2026-02-01',
    end_date: '2026-02-28',
    created_at: '2026-02-01',
  },
]

export const PRODUCT_TYPES = {
  ST: { label: 'Setup', color: 'gray' },
  CO: { label: 'Content', color: 'accent' },
  DS: { label: 'Design', color: 'coral' },
  OH: { label: 'Overhead', color: 'blue' },
}

export const PRIORITIES = ['Now', 'Hot All', 'Hot Area', 'Normal']
export const PROOF_STATUSES = ['Open', 'In Progress', 'Approved', 'Revise', 'No Go']
export const INV_STATUSES = ['Open', 'Sent', 'Paid']
export const COLLECT_STATUSES = ['Open', 'In Progress', 'Approved']
export const CLIENT_STATUSES = ['active', 'inactive']
